brand_name:
  default: ''
website_url:
  default: ''
logo_url:
  default: ''
mobile_logo_url:
  default: ''
links:
  type: list
  default: ''
inlinks:
  type: list
  default: ''
icons:
  type: list
  default: ''
custom_font_awesome_icons:
  type: list
  default: ''
